<?php

function its_protected_pages_report() {

  // skip if the content access module is not enabled
  if (!(module_exists('content_access'))) {
    drupal_set_message('content access not enabled');
	return;
  }

  // find all entries in the content access table
  $result = db_query("select nid, settings from {content_access}");

  $header = array('Node ID', 'Title', 'Service');
  $rows   = array();

  foreach ($result as $record) {

    $nid = $record->nid;
	$settings = unserialize($record->settings);

	$viewer_rids = $settings['view'];

    // skip nodes that are viewable by anonymous users
    if (in_array(DRUPAL_ANONYMOUS_RID, $viewer_rids)) {
	  continue;
    }

    $node = node_load($nid);

    // skip unpublished nodes
	if ($node->status == NODE_NOT_PUBLISHED) {
	  continue;
	}

    // skip nodes handling agreements - handled by a different team
	if ($node->type == 'agreement') {
	  continue;
    }

	// is there a service associated with this node?
	$service_name = 'None';

	if (property_exists($node, 'field_service')) {
      if (isset($node->field_service[LANGUAGE_NONE][0]['target_id'])) {
	    $service_id = $node->field_service[LANGUAGE_NONE][0]['target_id'];
	    $service    = node_load($service_id);
		$service_name = $service->title;
	  }
    }

    $rows[] = array($node->nid, l($node->title, 'node/' . $nid), $service_name);
  }

  // sort the rows by service name
  uasort($rows, 'cmp');

  return theme('table', array('header' => $header, 'rows' => $rows));
}

// sort by the third key (the service name) 
function cmp($a, $b) {
  if ($a == $b) {
    return 0;
  }
  return ($a[2] < $b[2]) ? -1 : 1;
}

function its_protected_pages_menu() {
  $items['reports/protected_pages'] = array(
    'title'         => 'Protected Pages Report',
    'page callback' => 'its_protected_pages_report',
    'access arguments' => array('bypass node access'),
//    'access callback' => TRUE,
  );
  return $items;
}
