<?php

function its_search_menu() {
  $items = array();

  $items['search'] = array(
    'title'           => 'Search',
	'page callback'   => 'its_search_search_page',
	'access callback' => TRUE,
  );

  return $items;
}

function its_search_search_page() {
  $output = '<gcse:search linktarget="_parent" queryparametername="q_as"></gcse:search>';
  return $output;
}

function its_search_block_info() {
  $blocks['its_search_search'] = array(
    'info' => t('Search box'),
	'status' => TRUE,
	'region' => 'search_box',
	'visibility' => BLOCK_VISIBILITY_NOTLISTED,
	'pages' => 'search',
  );

  return $blocks;
}

function its_search_block_view($delta = '') {
  switch ($delta) {
    case 'its_search_search':
      global $base_url;
	  $block['content'] = array(
	    '#markup' => '<gcse:searchbox-only linktarget="' . $base_url . '" queryparametername="q_as"></gcse:searchbox-only>',
      );
	  break;
  }
  return $block;
}


